server:
  port: 8093

spring:
  application:
    name: shop-member

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.101:3306/shop
    username: root
    password: 12345678

  session:
    store-type: redis
    timeout: 120

  redis:
    cluster:
      nodes:
        - 192.168.100.101:6379
        - 192.168.100.102:6379
        - 192.168.100.103:6379
        - 192.168.100.101:6380
        - 192.168.100.102:6380
        - 192.168.100.103:6380

    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/template/
    suffix: .html
    cache: false


mybatis:
  mapper-locations:
    - classpath*:mybatis/mapper/**/*.xml

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
